// GENERATED by bundle.sh — edit the source files, not this one.
// Paste the whole file into a DevTools console on a logged-in UT audits page.
// Exposes: poc, probe, verify, overhead, trim (see RUNBOOK.md).

// ===================================================================== planner-poc.js
/**
 * DAP-115 (5.1) POC harness — planner mechanics + preview timing.
 *
 * THROWAWAY SPIKE. Not imported by the extension, not typechecked, not shipped.
 * Delete once the findings land in docs/hypothetical-courses-design.md.
 *
 * Usage: open a logged-in https://utdirect.utexas.edu/apps/degree/audits/ tab,
 * paste this whole file into the DevTools console, then run (see RUNBOOK.md):
 *
 *   await poc.readPlanner()
 *   await poc.testAdd({ dept: "C S", num: "324E", ccyys: "20272" })
 *   await poc.testIdempotency({ dept: "C S", num: "324E", ccyys: "20272" })
 *   await poc.testParallelAdd([course1, course2, course3])
 *   await poc.testDelete(row)
 *   await poc.discoverModify()
 *   await poc.testExecutionContext()
 *   await poc.testAuthSignal()
 *   await poc.dumpAuditForm()   // inspect UT's audit forms
 *   await poc.timePreview(course, 5)
 *   poc.report()
 *   await poc.cleanup()
 *
 * Safety rules encoded here (from docs/hypothetical-courses-design.md):
 *   - page=4 is a state-changing GET. Never prefetched, never constructed by
 *     hand — always parsed from the page=3 listing.
 *   - action_code=A (Delete All) is never issued. Per-row deletes only —
 *     deleteAllCourses() wipes the planner via a per-row loop, so it stays
 *     inspectable and reports which rows resisted deletion.
 *   - Every mutation is recorded in poc.state.added so cleanup() can undo it.
 */

(() => {
  const BASE = "https://utdirect.utexas.edu/apps/degree/audits";
  const PLANNER_LIST = `${BASE}/planner/ut_course/`;
  const PLANNER_VIEW = `${BASE}/planner/view_planner/`;
  const HISTORY = `${BASE}/submissions/history/`;
  const NEW_AUDIT = `${BASE}/submissions/student_individual/`;

  const state = {
    added: [], // rows this session created, for cleanup()
    findings: {}, // question id -> answer, printed by report()
    timings: [], // one entry per timePreview() round trip
  };

  const log = (...args) => console.log("%c[poc]", "color:#bf5700", ...args);
  const warn = (...args) => console.warn("%c[poc]", "color:#bf5700", ...args);

  const now = () => performance.now();
  const record = (id, value) => {
    state.findings[id] = value;
    log(`finding ${id}:`, value);
    return value;
  };

  /**
   * Parse HTML where we can. MV3 service workers have no DOMParser (confirmed
   * 2026-08-16: `ReferenceError: DOMParser is not defined`), so there we fall
   * back to a regex-backed stub that answers only the selectors this harness
   * uses for auth/row detection. Enough for testExecutionContext() and
   * testAuthSignal(); the mutation helpers still need a real page.
   */
  function parseHtml(text) {
    if (typeof DOMParser !== "undefined") {
      return new DOMParser().parseFromString(text, "text/html");
    }
    const has = (re) => re.test(text);
    const stub = {
      title: (text.match(/<title[^>]*>([^<]*)/i) || [null, ""])[1].trim(),
      querySelector(sel) {
        if (/password/.test(sel)) {
          return has(/type=["']?password/i) ? {} : null;
        }
        if (/action_code=D/.test(sel)) return has(/action_code=D/) ? {} : null;
        return null;
      },
      querySelectorAll() {
        return [];
      },
      __stub: true,
    };
    return stub;
  }

  /** Credentialed GET returning a parsed document plus the raw response. */
  async function get(url) {
    const startedAt = now();
    const response = await fetch(url, { credentials: "include" });
    const text = await response.text();
    return {
      url,
      response,
      elapsedMs: now() - startedAt,
      doc: parseHtml(text),
      text,
    };
  }

  /**
   * Definitive logged-out evidence: UT bounced us to SSO, or served a login
   * form. Deliberately NOT `response.redirected` — the planner's own
   * page=4/action_code=D endpoints redirect on success, so treating any
   * redirect as logout aborts mid-mutation (it did: "Session died mid-add"
   * fired on a successful add).
   *
   * DAP-123 asks which signal is cheapest; `authSignals()` below reports all
   * of them per response so the answer comes from data, not from this guard.
   */
  function looksLoggedOut({ response, doc }) {
    const sso = /\b(login|signin|idp\.utexas|shib|sso)\b/i.test(response.url);
    return (
      sso ||
      response.status === 401 ||
      response.status === 403 ||
      Boolean(doc.querySelector('input[type="password"]'))
    );
  }

  /** Every candidate auth signal for one response — DAP-123's raw material. */
  function authSignals({ response, doc }) {
    return {
      status: response.status,
      ok: response.ok,
      redirected: response.redirected,
      finalUrl: response.url,
      ssoInUrl: /\b(login|signin|idp\.utexas|shib|sso)\b/i.test(response.url),
      hasPasswordInput: Boolean(doc.querySelector('input[type="password"]')),
      title: doc.title,
    };
  }

  // ---------------------------------------------------------------- read path

  /**
   * Parse View Courses into row keys. The row key is the triple the delete URL
   * needs: (key_course_id, key_course_ccyys, key_course_seq).
   */
  async function readPlanner() {
    const page = await get(PLANNER_VIEW);
    if (looksLoggedOut(page)) throw new Error("Not logged in — log in first.");

    const rows = [];
    for (const link of page.doc.querySelectorAll('a[href*="action_code=D"]')) {
      const params = new URL(link.getAttribute("href"), PLANNER_VIEW)
        .searchParams;
      const id = params.get("key_course_id");
      if (!id) continue;

      // UT parenthesizes expired rows; those don't apply to audits, so the
      // production client must reject them as preview inputs.
      const rowText = link.closest("tr")?.textContent?.trim() ?? "";
      rows.push({
        key_course_id: id,
        key_course_ccyys: params.get("key_course_ccyys"),
        key_course_seq: params.get("key_course_seq"),
        expired: /\(.*\)/.test(rowText),
        rowText: rowText.replace(/\s+/g, " "),
        deleteHref: link.getAttribute("href"),
      });
    }

    log(`planner has ${rows.length} row(s)`, rows);
    record("planner.rowCount", rows.length);
    record(
      "planner.seqValues",
      [...new Set(rows.map((r) => r.key_course_seq))].join(","),
    );
    return rows;
  }

  /**
   * Find the exact page=4 add link for a course on the page=3 listing.
   * Returns the href verbatim — never reconstructed.
   */
  async function resolveAddLink({
    dept,
    num,
    ccyys,
    courseType = "1",
    level = "U",
  }) {
    const listUrl =
      `${PLANNER_LIST}?page=3&course_ccyys=${encodeURIComponent(ccyys)}` +
      `&course_pass_fail=&s_pf=&course_type=${courseType}` +
      `&dpt=${encodeURIComponent(dept)}&s_lvl=${level}`;

    const page = await get(listUrl);
    if (looksLoggedOut(page)) throw new Error("Not logged in — log in first.");

    const candidates = [
      ...page.doc.querySelectorAll('a[href*="page=4"]'),
    ].filter((link) => {
      const linkNum = new URL(
        link.getAttribute("href"),
        PLANNER_LIST,
      ).searchParams.get("course_num");
      return linkNum?.trim() === num.trim();
    });

    if (!candidates.length) {
      throw new Error(`No page=4 link for ${dept} ${num} in ${ccyys}`);
    }
    // More than one match means a topic course; the design says never pick one
    // silently, so surface the choice instead of guessing.
    if (candidates.length > 1) {
      warn(
        `${dept} ${num} has ${candidates.length} add links (topic course?) — pick one manually`,
        candidates.map((c) => c.getAttribute("href")),
      );
    }

    return {
      href: candidates[0].getAttribute("href"),
      listElapsedMs: page.elapsedMs,
      candidateCount: candidates.length,
    };
  }

  // --------------------------------------------------------------- write path

  /**
   * Follow a parsed page=4 link. State-changing — only called deliberately.
   *
   * Never throws on a redirect: by the time this returns, UT may already have
   * written the row, so aborting here would strand a planner row the caller
   * doesn't know about. Whether the add worked is decided by re-reading the
   * planner (the caller's before/after diff), not by the response shape.
   */
  async function followAddLink(href) {
    const page = await get(new URL(href, PLANNER_LIST).toString());
    record("add.responseSignals", authSignals(page));

    if (looksLoggedOut(page)) {
      warn(
        "Add response looks like an SSO/login page — the row may or may not " +
          "have been written. Check View Courses before retrying.",
        authSignals(page),
      );
    }
    return page;
  }

  /**
   * DAP-122 steps 1: add a course and verify the row landed.
   * Records the new row so cleanup() can remove it.
   */
  async function testAdd(course) {
    const before = await readPlanner();
    const { href, candidateCount } = await resolveAddLink(course);
    log("resolved add link:", href);

    const startedAt = now();
    const addPage = await followAddLink(href);
    const after = await readPlanner();
    const addElapsedMs = now() - startedAt;

    const beforeKeys = new Set(before.map(rowKey));
    const newRows = after.filter((row) => !beforeKeys.has(rowKey(row)));

    record("add.works", newRows.length === 1);
    record("add.elapsedMs", Math.round(addElapsedMs));
    record("add.topicCandidates", candidateCount);
    record("add.responseStatus", addPage.response.status);

    state.added.push(...newRows);
    log(`add produced ${newRows.length} new row(s)`, newRows);

    if (!newRows.length) {
      warn(
        "Add wrote no new row. Either UT rejected it, or the course was " +
          "already in the planner (see add.idempotency). Response signals:",
        authSignals(addPage),
      );
    }
    return newRows[0];
  }

  /**
   * DAP-122 step 3: add the same course twice. Duplicate row or no-op?
   * Cleans up whatever the second add produced.
   */
  async function testIdempotency(course) {
    const before = await readPlanner();
    const { href } = await resolveAddLink(course);

    await followAddLink(href);
    const afterFirst = await readPlanner();
    await followAddLink(href);
    const afterSecond = await readPlanner();

    const delta1 = afterFirst.length - before.length;
    const delta2 = afterSecond.length - afterFirst.length;

    record(
      "add.idempotency",
      delta2 === 0
        ? "no-op (second add ignored)"
        : `duplicate row (+${delta2})`,
    );
    record("add.firstDelta", delta1);

    const beforeKeys = new Set(before.map(rowKey));
    const created = afterSecond.filter((row) => !beforeKeys.has(rowKey(row)));
    state.added.push(...created);
    return { delta1, delta2, created };
  }

  /**
   * Do concurrent adds work, or does UT need them serialized?
   *
   * The design doc assumes a serial queue ("sequential, fetch-before-write and
   * verify-after-write"). If parallel adds are safe, syncPlannerTo() could
   * fan out instead — worth knowing before 5.2 commits to serial.
   *
   * Watch for: rows silently dropped (fewer new rows than courses), duplicate
   * seq values, or interleaved seq assignment. Everything created is tracked
   * for cleanup().
   */
  async function testParallelAdd(courses) {
    if (!Array.isArray(courses) || courses.length < 2) {
      throw new Error("Pass at least 2 courses, e.g. [{dept,num,ccyys}, ...]");
    }

    // A missing row after a parallel run has two possible causes: a genuine
    // concurrency race, or UT rejecting that specific course on its own merits
    // (restricted, already taken, closed term). Those are indistinguishable
    // from the parallel run alone — so establish a serial baseline first and
    // only blame concurrency for courses that DO add one at a time.
    log("baseline: adding each course serially to see which UT accepts…");
    const baselineBefore = await readPlanner();
    const baselineKeys = new Set(baselineBefore.map(rowKey));
    const addsSerially = [];

    for (const course of courses) {
      const label = `${course.dept} ${course.num}`;
      try {
        const { href } = await resolveAddLink(course);
        await followAddLink(href);
        const rows = await readPlanner();
        const created = rows.filter((row) => !baselineKeys.has(rowKey(row)));
        state.added.push(...created);

        if (created.length) {
          addsSerially.push(label);
          // Undo immediately so the parallel phase starts from a clean slate.
          for (const row of created) {
            await testDelete(row);
            baselineKeys.delete(rowKey(row));
          }
        } else {
          warn(`${label} does not add even serially — UT rejects it`);
        }
      } catch (error) {
        warn(`${label} failed to resolve/add serially:`, error.message);
      }
    }
    record("add.serialBaseline", addsSerially);

    if (addsSerially.length < 2) {
      throw new Error(
        `Only ${addsSerially.length} of ${courses.length} courses add at all ` +
          `(${addsSerially.join(", ") || "none"}). Need >= 2 addable courses ` +
          "to test concurrency — pick different courses.",
      );
    }

    // Now the real test, restricted to courses proven to add serially.
    const testable = courses.filter((course) =>
      addsSerially.includes(`${course.dept} ${course.num}`),
    );
    log(`parallel phase: ${testable.length} course(s) known-addable`);

    const before = await readPlanner();
    const beforeKeys = new Set(before.map(rowKey));

    // Resolve first (read-only, safe to parallelize regardless) so the writes
    // fire as close together as possible — that's the race we're testing.
    const links = await Promise.all(testable.map((c) => resolveAddLink(c)));

    const startedAt = now();
    const settled = await Promise.allSettled(
      links.map(({ href }) => followAddLink(href)),
    );
    const elapsedMs = now() - startedAt;

    const after = await readPlanner();
    const created = after.filter((row) => !beforeKeys.has(rowKey(row)));
    state.added.push(...created);

    const seqValues = created.map((row) => row.key_course_seq);
    const result = {
      requested: testable.length,
      requestedCourses: testable.map((c) => `${c.dept} ${c.num}`),
      fulfilled: settled.filter((s) => s.status === "fulfilled").length,
      rowsCreated: created.length,
      allLanded: created.length === testable.length,
      duplicateSeq: seqValues.length !== new Set(seqValues).size,
      seqValues,
      elapsedMs: Math.round(elapsedMs),
    };
    record("add.parallel", result);

    if (!result.allLanded) {
      warn(
        `CONCURRENCY RACE: ${testable.length} courses that each add fine ` +
          `serially produced only ${created.length} rows in parallel. ` +
          "Planner writes must be serialized.",
      );
    } else if (result.duplicateSeq) {
      warn("Rows landed but seq values collided — writes must be serialized.");
    } else {
      log(
        `All ${created.length} parallel adds landed with distinct seq values. ` +
          "Re-run a couple of times before trusting this — races are flaky.",
      );
    }
    return result;
  }

  /** DAP-122 step 2: per-row delete. Never action_code=A. */
  async function testDelete(row) {
    if (!row) throw new Error("Pass a row from readPlanner()/testAdd().");

    const url =
      `${PLANNER_VIEW}?key_course_id=${encodeURIComponent(row.key_course_id)}` +
      `&key_course_ccyys=${encodeURIComponent(row.key_course_ccyys)}` +
      `&key_course_seq=${encodeURIComponent(row.key_course_seq)}` +
      `&action_code=D`;

    const before = await readPlanner();
    const startedAt = now();
    const page = await get(url);
    const after = await readPlanner();
    const elapsedMs = now() - startedAt;

    // Same reasoning as followAddLink: delete redirects on success, so the
    // planner diff decides the outcome, not the response shape.
    record("delete.responseSignals", authSignals(page));

    const removed = before.length - after.length;
    const targetGone = !after.some((r) => rowKey(r) === rowKey(row));

    record("delete.works", removed === 1 && targetGone);
    record("delete.elapsedMs", Math.round(elapsedMs));
    record("delete.removedExactlyOne", removed === 1);

    // Only forget the row once UT confirms it's gone — otherwise cleanup()
    // would lose track of a row still sitting in the planner.
    if (targetGone) {
      state.added = state.added.filter((r) => rowKey(r) !== rowKey(row));
    } else {
      warn("Delete did not remove the target row:", row, authSignals(page));
    }
    return { removed, targetGone };
  }

  /**
   * DAP-122 step 3: discover the Modify URL/form shape. Read-only — it only
   * reports the links/forms UT exposes for a row so we can name the params.
   */
  async function discoverModify() {
    const page = await get(PLANNER_VIEW);
    if (looksLoggedOut(page)) throw new Error("Not logged in — log in first.");

    const links = [...page.doc.querySelectorAll("a[href]")]
      .map((a) => a.getAttribute("href"))
      .filter((href) => /action_code=(?!D|A)|modify|page=5|page=6/i.test(href));

    const forms = [...page.doc.querySelectorAll("form")].map((form) => ({
      action: form.getAttribute("action"),
      method: form.getAttribute("method"),
      fields: [...form.elements].map((el) => ({
        name: el.name,
        type: el.type,
        value: el.value,
      })),
    }));

    record("modify.candidateLinks", links);
    record("modify.forms", forms);
    log("Inspect these, then follow the modify link manually in a tab.");
    return { links, forms };
  }

  // ------------------------------------------------- execution context + auth

  /**
   * DAP-123 step 4: does a planner GET work from the extension background
   * (no UT page origin) or only from a content script?
   *
   * Run this twice: once here (content-script/page context) and once from the
   * service-worker console (chrome://extensions → service worker → paste).
   * The two results together answer the ticket.
   */
  async function testExecutionContext() {
    const context =
      typeof window !== "undefined" && window.location?.hostname
        ? `page (${window.location.hostname})`
        : "worker/background";

    const page = await get(PLANNER_VIEW);
    const canParse = typeof DOMParser !== "undefined";
    const sawRows = Boolean(page.doc.querySelector('a[href*="action_code=D"]'));

    const result = {
      context,
      status: page.response.status,
      redirected: page.response.redirected,
      finalUrl: page.response.url,
      cookiesRodeAlong: !looksLoggedOut(page),
      domParserAvailable: canParse,
      parsedPlannerRows: sawRows,
    };
    record(`executionContext.${context}`, result);
    return result;
  }

  /** DAP-123 step 5: which signal detects logged-out most cheaply? */
  async function testAuthSignal() {
    const page = await get(HISTORY);
    const signals = {
      "response.redirected": page.response.redirected,
      "!response.ok": !page.response.ok,
      status: page.response.status,
      "response.url": page.response.url,
      "url !== requested": page.response.url !== HISTORY,
      "password input in DOM": Boolean(
        page.doc.querySelector('input[type="password"]'),
      ),
      elapsedMs: Math.round(page.elapsedMs),
      bytes: page.text.length,
    };
    record("auth.signalsWhileLoggedIn", signals);
    log(
      "Now log out (or open an incognito window) and re-run testAuthSignal() " +
        "to see which of these flips. The cheapest one that flips wins.",
    );
    return signals;
  }

  // ------------------------------------------------------------------- timing

  /** Raw history IDs, before the major+percentage dedupe the UI applies. */
  async function rawHistoryIds() {
    const page = await get(HISTORY);
    if (looksLoggedOut(page)) throw new Error("Not logged in — log in first.");

    const ids = [];
    for (const row of page.doc.querySelectorAll("table tbody tr")) {
      const cells = row.querySelectorAll("td");
      if (cells.length < 8) continue;
      const id = cells[6].querySelector("a")?.textContent?.trim();
      if (id) ids.push(id);
    }
    return { ids, elapsedMs: page.elapsedMs };
  }

  /**
   * Pick the audit form. The submit page carries several forms (site search,
   * nav); the first one is not the audit form — that mistake is why the
   * Planned Courses checkbox came up missing on the first run. Prefer the form
   * that owns the run button, then fall back to the one with the most fields.
   */
  function findAuditForm(doc) {
    const forms = [...doc.querySelectorAll("form")];
    if (!forms.length) throw new Error("No form on the audit submit page.");

    // Identify by contents, not by "has a submit button" — UT's site search
    // form also has one, and it sorts first. (That mistake produced
    // `checkboxCandidates: []`: the search form has no checkboxes at all.)
    //
    // The real audit form, confirmed 2026-08-05, carries a checkbox named
    // `planned` and a submit named `audit`. A sibling "test profile" form
    // shares some field names but has NO checkboxes, so requiring the
    // checkbox distinguishes them.
    const byPlannedCheckbox = forms.find((form) =>
      form.querySelector('input[type="checkbox"][name="planned"]'),
    );
    if (byPlannedCheckbox) return byPlannedCheckbox;

    const byAuditSubmit = forms.find((form) =>
      form.querySelector('[name="audit"][type="submit"]'),
    );
    if (byAuditSubmit) return byAuditSubmit;

    // Last resort: the form with the most checkboxes, since the audit form is
    // the only one on the page offering include-options.
    const byCheckboxCount = [...forms].sort(
      (a, b) =>
        b.querySelectorAll('input[type="checkbox"]').length -
        a.querySelectorAll('input[type="checkbox"]').length,
    )[0];
    if (byCheckboxCount?.querySelector('input[type="checkbox"]')) {
      return byCheckboxCount;
    }
    throw new Error(
      "Could not identify the audit form — run poc.dumpAuditForm() and check " +
        "whether UT changed the page.",
    );
  }

  /** Label text associated with a form control, however UT wired it up. */
  function labelFor(input, form) {
    return (
      input.closest("label")?.textContent ??
      (input.id
        ? form.querySelector(`label[for="${input.id}"]`)?.textContent
        : null) ??
      input.closest("td")?.parentElement?.textContent ??
      input.parentElement?.textContent ??
      ""
    );
  }

  /**
   * Diagnostic: dump every form on the audit submit page with its method,
   * action, and fields. Read-only. Run this to identify the Planned Courses
   * checkbox by name when auto-discovery misses it.
   */
  async function dumpAuditForm() {
    const page = await get(NEW_AUDIT);
    if (looksLoggedOut(page)) throw new Error("Not logged in — log in first.");

    const forms = [...page.doc.querySelectorAll("form")].map((form, index) => ({
      index,
      method: (form.getAttribute("method") || "GET").toUpperCase(),
      action: form.getAttribute("action"),
      fieldCount: form.elements.length,
      fields: [...form.elements].map((el) => ({
        name: el.name,
        type: el.type,
        value: el.value,
        checked: el.checked,
        label: labelFor(el, form).replace(/\s+/g, " ").trim().slice(0, 80),
      })),
    }));

    console.log(JSON.stringify(forms, null, 2));
    record("submit.formDump", forms);
    log(
      "Find the Planned Courses checkbox above, then pass its name:\n" +
        '  await poc.timePreview(course, 5, { plannedCheckboxName: "THE_NAME" })',
    );
    return forms;
  }

  /**
   * The default-degree "Run Audit" form — what UT's `.run_button` submits and
   * what the extension's background controller clicks (DAP-105).
   *
   * Found 2026-08-16 via dumpAuditForm(): form index 1 of 3, POST to
   * `/apps/degree/audits/requests/test_profile_button/`, all-hidden fields:
   * csrfmiddlewaretoken, student_eid, degree_plan, catalog, minor,
   * effective_ccyys, incl_current_crswk ("Y"), incl_future_crswk ("Y"),
   * incl_planned_crswk (" " = off). The visible `current/future/planned`
   * checkboxes belong to the *custom* audit form and only drive UI; posting
   * that form with its empty catalog/college/degree_plan selects makes UT
   * re-render it (200, no redirect) and queue nothing — which is why the first
   * timing runs never saw a new audit ID.
   */
  function findDefaultAuditForm(doc) {
    return [...doc.querySelectorAll("form")].find(
      (form) =>
        /test_profile_button/.test(form.getAttribute("action") ?? "") ||
        form.querySelector('[name="incl_planned_crswk"]'),
    );
  }

  /**
   * Submit a planned-inclusive audit for the student's default degree plan by
   * posting the same form UT's Run Audit button posts, with
   * `incl_planned_crswk=Y`. Returns when the submit response comes back —
   * generation continues server-side, so the caller polls history for the new
   * raw ID. On success UT redirects to `history/?submit_success=Y`; that's
   * recorded so a silent rejection (200, still on the submit page) is visible.
   */
  async function submitPlannedAudit({ plannedCheckboxName = "planned" } = {}) {
    const page = await get(NEW_AUDIT);
    if (looksLoggedOut(page)) throw new Error("Not logged in — log in first.");

    const defaultForm = findDefaultAuditForm(page.doc);
    if (defaultForm) {
      const params = new URLSearchParams();
      for (const el of defaultForm.elements) {
        if (!el.name || el.disabled) continue;
        params.append(el.name, el.value ?? "");
      }
      params.set("incl_planned_crswk", "Y");
      record("submit.form", "test_profile_button (default degree)");
      record("submit.plannedField", "incl_planned_crswk=Y");

      const action = new URL(
        defaultForm.getAttribute("action") || "",
        NEW_AUDIT,
      );
      const csrf = params.get("csrfmiddlewaretoken");
      const startedAt = now();
      const response = await fetch(action.toString(), {
        method: "POST",
        credentials: "include",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          ...(csrf ? { "X-CSRFToken": csrf } : {}),
        },
        body: params,
      });
      const text = await response.text();
      const elapsedMs = now() - startedAt;

      if (response.status === 403 || /CSRF/i.test(text.slice(0, 2000))) {
        record("submit.csrfRejected", true);
        throw new Error(
          `Audit submit rejected (${response.status}) — likely CSRF. Run this ` +
            "from a console on the UT audit page itself so the Referer matches.",
        );
      }
      // Observed 2026-08-16: a successful post redirects to
      // `/apps/degree/audits/requests/history/` (no `submit_success=Y` on this
      // path). A silent rejection stays on the submit page instead.
      const accepted =
        response.redirected && /\/history\/?(\?|$)/.test(response.url);
      record("submit.acceptedRedirect", accepted);
      record("submit.landedOn", response.url);
      if (!accepted) {
        warn(
          "Submit did not redirect to a history page — UT probably rejected " +
            "it silently. Response landed on:",
          response.url,
        );
      }
      return {
        elapsedMs,
        status: response.status,
        method: "POST",
        submittedUrl: response.url,
        accepted,
      };
    }

    // Fallback (pre-2026-08-16 path): drive the custom audit form's checkbox.
    // Kept only so the harness still reports *something* if UT removes the
    // default-degree button; expect it to be rejected unless the catalog/
    // college/degree_plan selects are filled in.
    warn("default-degree form not found — falling back to custom audit form");
    const form = findAuditForm(page.doc);
    const method = (form.getAttribute("method") || "GET").toUpperCase();

    const params = new URLSearchParams();
    for (const el of form.elements) {
      if (!el.name || el.disabled) continue;
      if (el.type === "checkbox" || el.type === "radio") {
        if (el.checked) params.append(el.name, el.value || "on");
        continue;
      }
      // Named submit buttons are how Django tells which action fired, so the
      // form's own submit must be included — UT's is `audit=Submit Audit`.
      if (el.type === "submit") {
        if (el.name) params.append(el.name, el.value ?? "");
        continue;
      }
      if (el.type === "button") continue;
      params.append(el.name, el.value ?? "");
    }

    // The Planned Courses checkbox is unchecked by default; our runs must
    // always set it. Match by name first (UT calls it `planned`), then fall
    // back to label text for resilience if UT renames it.
    const checkboxes = [...form.querySelectorAll('input[type="checkbox"]')];
    const plannedInput =
      checkboxes.find((input) => input.name === plannedCheckboxName) ??
      checkboxes.find((input) => /planned/i.test(labelFor(input, form)));

    if (!plannedInput) {
      record("submit.plannedCheckboxFound", false);
      record(
        "submit.checkboxCandidates",
        checkboxes.map((input) => ({
          name: input.name,
          value: input.value,
          label: labelFor(input, form).replace(/\s+/g, " ").trim().slice(0, 80),
        })),
      );
      // Without the checkbox the run excludes planned courses, so the timing
      // would measure the wrong thing entirely. Refuse rather than mislead.
      throw new Error(
        "Planned Courses checkbox not found — run `await poc.dumpAuditForm()`, " +
          "then pass { plannedCheckboxName } to timePreview().",
      );
    }

    record("submit.plannedCheckboxFound", true);
    record("submit.plannedCheckboxName", plannedInput.name);
    record("submit.formMethod", method);
    // value="X" on UT's checkboxes — send exactly that, not "on".
    params.set(plannedInput.name, plannedInput.value || "on");

    // action="" means "post to this same URL", which `new URL("", base)`
    // already resolves correctly.
    const action = new URL(form.getAttribute("action") || "", NEW_AUDIT);

    const startedAt = now();
    let response;
    if (method === "GET") {
      action.search = params.toString();
      response = await fetch(action.toString(), { credentials: "include" });
    } else {
      // Django checks the CSRF token in a header as well as the body, and
      // rejects POSTs whose Referer doesn't match over HTTPS.
      const csrf = params.get("csrfmiddlewaretoken");
      response = await fetch(action.toString(), {
        method,
        credentials: "include",
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          ...(csrf ? { "X-CSRFToken": csrf } : {}),
        },
        body: params,
      });
    }
    const text = await response.text();

    // A Django CSRF rejection comes back as 403 with an explanatory page, not
    // as a network error — surface it instead of silently polling for an
    // audit that was never queued.
    if (response.status === 403 || /CSRF/i.test(text.slice(0, 2000))) {
      record("submit.csrfRejected", true);
      throw new Error(
        `Audit submit rejected (${response.status}) — likely CSRF. Run this ` +
          "from a console on the UT audit page itself so the Referer matches.",
      );
    }
    return {
      elapsedMs: now() - startedAt,
      status: response.status,
      method,
      submittedUrl: response.url,
    };
  }

  /** Poll raw history until an ID appears that wasn't in `before`. */
  async function pollForNewAuditId(before, { windowMs = 90_000 } = {}) {
    const known = new Set(before);
    const startedAt = now();
    const deadline = startedAt + windowMs;

    while (now() < deadline) {
      const { ids } = await rawHistoryIds();
      const fresh = ids.find((id) => !known.has(id));
      if (fresh) return { auditId: fresh, elapsedMs: now() - startedAt };
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
    throw new Error(`No new audit ID within ${windowMs}ms`);
  }

  async function scrapeAudit(auditId) {
    const startedAt = now();
    const page = await get(`${BASE}/results/${auditId}/`);
    if (looksLoggedOut(page)) throw new Error("Session died mid-scrape.");
    return {
      elapsedMs: now() - startedAt,
      // Rough proof the page really is an audit, without importing the parser.
      requirementRows: page.doc.querySelectorAll("tr").length,
    };
  }

  /**
   * DAP-124: one full preview round trip, per-stage. Adds the course, runs a
   * planned-inclusive audit, polls for the new raw ID, scrapes it, then
   * deletes the course again so the planner is left as found.
   */
  async function timeOnePreview(course, { plannedCheckboxName } = {}) {
    const t = {};
    const total = now();

    // Snapshot first: cleanup below must only ever touch rows THIS run created.
    // Matching by course number alone would delete a pre-existing row for the
    // same course, which the ticket explicitly forbids.
    const before = await readPlanner();
    const beforeKeys = new Set(before.map(rowKey));
    let created = [];

    try {
      const resolveStart = now();
      const { href } = await resolveAddLink(course);
      t.resolveMs = now() - resolveStart;

      const addStart = now();
      await followAddLink(href);
      const rows = await readPlanner();
      t.addMs = now() - addStart;

      created = rows.filter((row) => !beforeKeys.has(rowKey(row)));
      // Track immediately: if a later stage throws, cleanup() must still know
      // about this row. (Before this, a submit failure leaked a row per run.)
      state.added.push(...created);
      if (created.length !== 1) {
        warn(`expected exactly 1 new row, got ${created.length}`, created);
      }

      const beforeIds = (await rawHistoryIds()).ids;

      const submit = await submitPlannedAudit({ plannedCheckboxName });
      t.submitMs = submit.elapsedMs;

      const polled = await pollForNewAuditId(beforeIds);
      t.generateMs = polled.elapsedMs;

      const scraped = await scrapeAudit(polled.auditId);
      t.scrapeMs = scraped.elapsedMs;

      t.auditId = polled.auditId;
      t.requirementRows = scraped.requirementRows;
      t.totalMs = now() - total;
      state.timings.push(t);
      log("round trip", t);
      return t;
    } finally {
      // Always undo this run's planner write, however the round trip ended.
      // A failed run that leaves rows behind poisons every later measurement
      // and the planner itself.
      if (created.length === 1) {
        const added = created[0];
        const deleteStart = now();
        try {
          await get(
            `${PLANNER_VIEW}?key_course_id=${encodeURIComponent(added.key_course_id)}` +
              `&key_course_ccyys=${encodeURIComponent(added.key_course_ccyys)}` +
              `&key_course_seq=${encodeURIComponent(added.key_course_seq)}` +
              `&action_code=D`,
          );
          t.deleteMs = now() - deleteStart;

          const after = await readPlanner();
          if (after.some((row) => rowKey(row) === rowKey(added))) {
            warn("planner not restored — row survived delete", added);
          } else {
            state.added = state.added.filter(
              (row) => rowKey(row) !== rowKey(added),
            );
          }
        } catch (error) {
          warn("cleanup delete failed — run poc.cleanup()", error);
        }
      }
    }
  }

  /** Run N round trips back to back and print the p50/p95 table. */
  async function timePreview(course, runs = 5, options = {}) {
    let consecutiveFailures = 0;
    for (let i = 0; i < runs; i++) {
      log(`--- round trip ${i + 1}/${runs}`);
      try {
        await timeOnePreview(course, options);
        consecutiveFailures = 0;
      } catch (error) {
        warn(`round trip ${i + 1} failed:`, error);
        // Every run mutates the real planner and UT's audit log. If the first
        // two fail the same way, the rest will too — stop instead of grinding
        // through five identical failures (that's what produced an empty
        // timing table and a planner full of leftover rows).
        if (++consecutiveFailures >= 2) {
          warn(`stopping after ${consecutiveFailures} consecutive failures`);
          break;
        }
      }
    }
    return timingTable();
  }

  function percentile(values, p) {
    if (!values.length) return NaN;
    const sorted = [...values].sort((a, b) => a - b);
    const index = Math.min(
      sorted.length - 1,
      Math.ceil((p / 100) * sorted.length) - 1,
    );
    return Math.round(sorted[index]);
  }

  function timingTable() {
    const stages = [
      "resolveMs",
      "addMs",
      "submitMs",
      "generateMs",
      "scrapeMs",
      "deleteMs",
      "totalMs",
    ];
    const table = {};
    for (const stage of stages) {
      const values = state.timings
        .map((t) => t[stage])
        .filter((v) => typeof v === "number");
      if (!values.length) continue;
      table[stage] = {
        n: values.length,
        p50: percentile(values, 50),
        p95: percentile(values, 95),
        min: Math.round(Math.min(...values)),
        max: Math.round(Math.max(...values)),
      };
    }
    console.table(table);

    const p95Total = table.totalMs?.p95;
    if (p95Total > 15_000) {
      warn(
        `p95 total ${p95Total}ms exceeds the 15s threshold — flag DAP-114; ` +
          "this reopens the eager-verify decision.",
      );
    }
    record("timing.table", table);
    return table;
  }

  // ------------------------------------------------------------------ cleanup

  const rowKey = (row) =>
    `${row.key_course_id}|${row.key_course_ccyys}|${row.key_course_seq}`;

  /** Delete every row this session added. Per-row only; never action_code=A. */
  async function cleanup() {
    if (!state.added.length) {
      log("nothing to clean up");
      return [];
    }
    const results = [];
    for (const row of [...state.added]) {
      try {
        results.push(await testDelete(row));
      } catch (error) {
        warn("cleanup failed for", row, error);
      }
    }
    const remaining = await readPlanner();
    log(`cleanup done — planner now has ${remaining.length} row(s)`);
    return results;
  }

  /**
   * Wipe every row via per-row deletes, after snapshotting what was there.
   *
   * Deliberately NOT `action_code=A`. Same end state, but UT's Delete All is a
   * single irreversible call with no record of what it removed; this loop
   * prints a restorable snapshot first and reports exactly which rows resisted
   * deletion. UT has no undo, so the snapshot is the only way back.
   *
   * Requires an explicit confirmation string so a stray paste can't fire it:
   *   await poc.deleteAllCourses("DELETE ALL")
   */
  async function deleteAllCourses(confirmation) {
    if (confirmation !== "DELETE ALL") {
      throw new Error(
        'Refusing: call poc.deleteAllCourses("DELETE ALL") to confirm. ' +
          "This removes every planner row, including ones you added by hand.",
      );
    }

    const before = await readPlanner();
    if (!before.length) {
      log("planner is already empty");
      return { deleted: [], failed: [], snapshot: [] };
    }

    // Print the restore list BEFORE touching anything — if a delete misfires,
    // this console output is the only record of what the planner held.
    const snapshot = before.map((row) => ({
      key_course_id: row.key_course_id,
      key_course_ccyys: row.key_course_ccyys,
      key_course_seq: row.key_course_seq,
      rowText: row.rowText,
    }));
    warn(
      `About to delete ${before.length} row(s). SNAPSHOT (save this to re-add ` +
        "them — UT has no undo):",
    );
    console.log(JSON.stringify(snapshot, null, 2));
    record("deleteAll.snapshot", snapshot);

    const deleted = [];
    const failed = [];
    for (const row of before) {
      try {
        const { targetGone } = await testDelete(row);
        (targetGone ? deleted : failed).push(row);
      } catch (error) {
        warn("delete failed for", row, error);
        failed.push(row);
      }
    }

    const after = await readPlanner();
    record("deleteAll.result", {
      requested: before.length,
      deleted: deleted.length,
      failed: failed.length,
      remaining: after.length,
    });
    if (failed.length) {
      warn(`${failed.length} row(s) could not be deleted:`, failed);
    }
    log(`delete-all done — ${deleted.length} removed, ${after.length} remain`);
    return { deleted, failed, snapshot };
  }

  /**
   * Re-add courses from a deleteAllCourses() snapshot. Best-effort recovery:
   * seq numbers are UT-assigned, so restored rows get new ones, and the
   * original term must still be open. Parses course id back into dept + number
   * (`C S324E` → dept `C S`, num `324E`).
   */
  async function restoreFromSnapshot(snapshot) {
    if (!Array.isArray(snapshot) || !snapshot.length) {
      throw new Error("Pass the snapshot array printed by deleteAllCourses().");
    }

    const restored = [];
    const failed = [];
    for (const entry of snapshot) {
      // Course numbers start at the first digit; everything before is the dept.
      const match = entry.key_course_id.match(/^(.*?)(\d.*)$/);
      if (!match) {
        failed.push({ entry, reason: "could not split dept/number" });
        continue;
      }
      const [, dept, num] = match;
      try {
        const { href } = await resolveAddLink({
          dept: dept.trim(),
          num,
          ccyys: entry.key_course_ccyys,
        });
        await followAddLink(href);
        restored.push(`${dept.trim()} ${num}`);
      } catch (error) {
        failed.push({ entry, reason: error.message });
      }
    }

    const after = await readPlanner();
    log(`restore: ${restored.length} re-added, ${failed.length} failed`);
    if (failed.length) warn("could not restore:", failed);
    return { restored, failed, rows: after };
  }

  function report() {
    log("=== DAP-115 findings ===");
    console.log(JSON.stringify(state.findings, null, 2));
    if (state.timings.length) timingTable();
    if (state.added.length) {
      warn(
        `${state.added.length} row(s) still in the planner from this session — ` +
          "run poc.cleanup()",
      );
    }
    return state.findings;
  }

  globalThis.poc = {
    state,
    readPlanner,
    resolveAddLink,
    testAdd,
    testIdempotency,
    testParallelAdd,
    testDelete,
    discoverModify,
    testExecutionContext,
    testAuthSignal,
    rawHistoryIds,
    dumpAuditForm,
    submitPlannedAudit,
    timeOnePreview,
    timePreview,
    timingTable,
    cleanup,
    deleteAllCourses,
    restoreFromSnapshot,
    report,
  };

  log(
    "ready — see scripts/spike/RUNBOOK.md. Start with: await poc.readPlanner()",
  );
})();

// ===================================================================== generate-timing-probe.js
/**
 * DAP-124 follow-up: is `generateMs` really UT's audit generation time?
 *
 * The original harness polled history/ every 500ms and counted an audit "done"
 * only once its ID cell contained a LINK. UT shows a queued request as a row
 * (now with a "Processing"-style status) before that link renders, so the old
 * number bundled: real generation + time-to-link + poll quantization + fetch
 * overhead. Observed generation is ~1-2s, so that ~5.2s figure is suspect.
 *
 * This probe separates the events and polls ~3x finer:
 *   rowVisibleMs      - request row appears (UT accepted the job)
 *   processingSeenMs  - row shows a processing/pending status
 *   linkReadyMs       - ID becomes clickable (result actually ready)
 *   resultsFetchMs    - the results page itself returns content
 *
 * Read-only apart from whatever submit YOU trigger. Paste into a DevTools
 * console on a logged-in utdirect.utexas.edu audits page.
 */
(() => {
  const BASE = "https://utdirect.utexas.edu/apps/degree/audits";
  const HISTORY = `${BASE}/submissions/history/`;
  const now = () => performance.now();
  const log = (...a) => console.log("%c[probe]", "color:#bf5700", ...a);

  // Any of these in a row's text means "UT is still working on it".
  const PROCESSING_RE = /process|pending|progress|running|queue|wait/i;

  async function get(url) {
    const r = await fetch(url, { credentials: "include" });
    const t = await r.text();
    return { r, doc: new DOMParser().parseFromString(t, "text/html") };
  }

  /**
   * Snapshot every history row. Keeps the full row text so an intermediate
   * "Processing" state is visible even before any link exists — the original
   * harness skipped such rows entirely and so could not see them.
   */
  async function historyRows() {
    const { doc } = await get(HISTORY);
    const rows = [];
    for (const tr of doc.querySelectorAll("table tbody tr")) {
      const cells = tr.querySelectorAll("td");
      if (cells.length < 8) continue;
      const idCell = cells[6];
      const rowText = tr.textContent.replace(/\s+/g, " ").trim();
      rows.push({
        // Row identity that exists even before the link does.
        key: [...cells]
          .slice(0, 6)
          .map((c) => c.textContent.trim())
          .join("|"),
        idText: idCell.textContent.trim(),
        linked: Boolean(idCell.querySelector("a")),
        auditId: idCell.querySelector("a")?.textContent?.trim() ?? null,
        processing: PROCESSING_RE.test(rowText),
        rowText,
      });
    }
    return rows;
  }

  /**
   * One-shot: what does a freshly-refreshed history page look like right now?
   * Run this WHILE an audit generates to see the intermediate state verbatim —
   * that reveals the exact wording to poll for.
   */
  async function inspectNow() {
    const rows = await historyRows();
    console.table(
      rows.map((r) => ({
        idText: r.idText,
        linked: r.linked,
        processing: r.processing,
        rowText: r.rowText.slice(0, 90),
      })),
    );
    return rows;
  }

  /**
   * Call IMMEDIATELY after submitting an audit. Pass the row snapshot taken
   * BEFORE the submit.
   */
  async function watch(
    beforeRows,
    { windowMs = 90_000, intervalMs = 150 } = {},
  ) {
    const beforeKeys = new Set(beforeRows.map((r) => r.key));
    const t0 = now();
    let tRow = null;
    let tProcessing = null;
    let tLink = null;
    let newRow = null;
    let polls = 0;
    const deadline = t0 + windowMs;

    while (now() < deadline) {
      polls++;
      const rows = await historyRows();
      const fresh = rows.find((r) => !beforeKeys.has(r.key));

      if (fresh && tRow === null) {
        tRow = now() - t0;
        newRow = fresh;
        log(
          `ROW appeared @ ${Math.round(tRow)}ms — linked=${fresh.linked}, ` +
            `processing=${fresh.processing}`,
        );
        log(`   row text: ${fresh.rowText.slice(0, 120)}`);
      }
      if (fresh?.processing && tProcessing === null) {
        tProcessing = now() - t0;
        log(`PROCESSING seen @ ${Math.round(tProcessing)}ms`);
      }
      if (fresh?.linked && tLink === null) {
        tLink = now() - t0;
        newRow = fresh;
        log(`LINK ready @ ${Math.round(tLink)}ms — auditId=${fresh.auditId}`);
        break;
      }
      await new Promise((r) => setTimeout(r, intervalMs));
    }

    if (tRow === null) {
      log("no new row appeared within the window");
      return null;
    }

    let tFetch = null;
    let rowsParsed = null;
    if (newRow?.auditId) {
      const s = now();
      const { doc } = await get(`${BASE}/results/${newRow.auditId}/`);
      tFetch = now() - s;
      rowsParsed = doc.querySelectorAll("tr").length;
      log(
        `results page fetched in ${Math.round(tFetch)}ms (${rowsParsed} rows)`,
      );
    }

    const out = {
      rowVisibleMs: tRow === null ? null : Math.round(tRow),
      processingSeenMs: tProcessing === null ? null : Math.round(tProcessing),
      linkReadyMs: tLink === null ? null : Math.round(tLink),
      // The interval the old harness was blind to.
      queuedButNotReadyMs:
        tRow !== null && tLink !== null ? Math.round(tLink - tRow) : null,
      resultsFetchMs: tFetch === null ? null : Math.round(tFetch),
      polls,
      pollIntervalMs: intervalMs,
    };
    console.table([out]);
    return out;
  }

  /**
   * How fast can we poll history/ before UT pushes back? Answers "can we poll
   * faster" with data instead of a guess: N sequential fetches as fast as they
   * complete, reporting latency and any non-200s. Read-only.
   */
  async function pollRateTest(n = 10) {
    const times = [];
    const statuses = new Set();
    const start = now();
    for (let i = 0; i < n; i++) {
      const s = now();
      const { r } = await get(HISTORY);
      times.push(now() - s);
      statuses.add(r.status);
    }
    const sorted = [...times].sort((a, b) => a - b);
    const avg = (xs) => Math.round(xs.reduce((a, b) => a + b, 0) / xs.length);
    const out = {
      requests: n,
      wallClockMs: Math.round(now() - start),
      minMs: Math.round(sorted[0]),
      medianMs: Math.round(sorted[Math.floor(n / 2)]),
      maxMs: Math.round(sorted[n - 1]),
      statuses: [...statuses].join(","),
      firstThreeAvg: avg(times.slice(0, 3)),
      lastThreeAvg: avg(times.slice(-3)),
    };
    console.table([out]);
    if (out.statuses !== "200") {
      log("NON-200 seen — back off, do not poll this fast");
    } else if (out.lastThreeAvg > out.firstThreeAvg * 1.8) {
      log("latency climbing — likely throttling; keep the interval at 500ms");
    } else {
      log("no pushback back-to-back; a ~250-300ms interval looks safe");
    }
    return out;
  }

  globalThis.probe = { historyRows, watch, inspectNow, pollRateTest };
  log(
    "ready. Usage:\n" +
      "  const before = await probe.historyRows();\n" +
      "  await poc.submitPlannedAudit();   // or click Run Audit\n" +
      "  await probe.watch(before);\n" +
      "  await probe.pollRateTest();       // how fast can we poll?\n" +
      "  await probe.inspectNow();         // run mid-generation",
  );
})();

// ===================================================================== timing-verify.js
/**
 * DAP-124 verification: are the ~3s generation timings trustworthy, and how
 * fast can we actually detect completion?
 *
 * Three questions, three tools:
 *   1. cacheCheck()   - is the history page being served stale? (correctness)
 *   2. verifyTiming() - n=1 is not a measurement. Repeat it, with cache
 *                       defeated and server-side timestamps captured.
 *   3. Both report whether a delayed first poll is safe.
 *
 * Read-only apart from the submits YOU trigger via the callback.
 * Paste alongside planner-poc.js on a logged-in UT audits page.
 */
(() => {
  const BASE = "https://utdirect.utexas.edu/apps/degree/audits";
  const HISTORY = `${BASE}/submissions/history/`;
  const now = () => performance.now();
  const log = (...a) => console.log("%c[verify]", "color:#bf5700", ...a);
  const warn = (...a) => console.warn("%c[verify]", "color:#bf5700", ...a);

  const PROCESSING_RE = /in progress|process|pending|running|queue|submitted/i;

  /**
   * Cache-defeating fetch. Three layers, because any one can fail:
   *   - cache: "no-store"      tells Chrome not to use or write the HTTP cache
   *   - Cache-Control header   asks intermediaries not to serve stale
   *   - unique query param     defeats anything keying purely on URL
   * Returns server-side cache headers so we can SEE whether it mattered.
   */
  async function getFresh(url, { bustQuery = true } = {}) {
    const u = new URL(url);
    if (bustQuery) u.searchParams.set("_poc", String(Math.random()).slice(2));
    const r = await fetch(u.toString(), {
      credentials: "include",
      cache: "no-store",
      headers: { "Cache-Control": "no-cache", Pragma: "no-cache" },
    });
    const t = await r.text();
    return {
      r,
      text: t,
      doc: new DOMParser().parseFromString(t, "text/html"),
      headers: {
        date: r.headers.get("date"),
        age: r.headers.get("age"),
        cacheControl: r.headers.get("cache-control"),
        etag: r.headers.get("etag"),
        lastModified: r.headers.get("last-modified"),
      },
    };
  }

  function parseRows(doc) {
    const rows = [];
    for (const tr of doc.querySelectorAll("table tbody tr")) {
      const cells = tr.querySelectorAll("td");
      if (cells.length < 8) continue;
      const idCell = cells[6];
      const rowText = tr.textContent.replace(/\s+/g, " ").trim();
      rows.push({
        key: [...cells]
          .slice(0, 6)
          .map((c) => c.textContent.trim())
          .join("|"),
        linked: Boolean(idCell.querySelector("a")),
        auditId: idCell.querySelector("a")?.textContent?.trim() ?? null,
        processing: PROCESSING_RE.test(rowText),
        rowText,
      });
    }
    return rows;
  }

  /**
   * QUESTION 1 — is the history page cached?
   *
   * Compares a plain fetch against a cache-defeating one, and reports the
   * server's own cache headers. If `age` is non-zero or the two responses
   * differ in length, the plain path was serving stale HTML and every previous
   * timing is suspect.
   */
  async function cacheCheck() {
    const plain = await fetch(HISTORY, { credentials: "include" });
    const plainText = await plain.text();
    const fresh = await getFresh(HISTORY);

    const out = {
      plainBytes: plainText.length,
      freshBytes: fresh.text.length,
      identical: plainText.length === fresh.text.length,
      serverDate: fresh.headers.date,
      age: fresh.headers.age ?? "(none)",
      cacheControl: fresh.headers.cacheControl ?? "(none)",
      etag: fresh.headers.etag ?? "(none)",
    };
    console.table([out]);

    const ageNum = Number(fresh.headers.age ?? 0);
    if (ageNum > 0) {
      warn(
        `Age: ${ageNum}s — a cache IS serving stale content. Timings are suspect.`,
      );
    } else if (
      /no-store|no-cache|max-age=0/i.test(fresh.headers.cacheControl ?? "")
    ) {
      log(
        "Server says no-cache/no-store — responses are generated per request.",
      );
    } else {
      log(
        "No Age header and no explicit no-cache. Likely uncached, but the " +
          "cache-busted fetch is used for measurement regardless.",
      );
    }
    return out;
  }

  /**
   * QUESTION 2 — repeat the measurement properly.
   *
   * `submitFn` must trigger ONE audit submit (e.g. () => poc.submitPlannedAudit()).
   * Each run: snapshot -> submit -> poll with cache defeated until the ID links.
   *
   * Also captures the server's `Date` header at row-appearance and at
   * link-ready. That's a SERVER-side clock, independent of our poll loop, so it
   * cross-checks the client timing at 1-second granularity.
   */
  async function verifyTiming(submitFn, runs = 3, { intervalMs = 150 } = {}) {
    if (typeof submitFn !== "function") {
      throw new Error(
        "Pass a submit function, e.g. () => poc.submitPlannedAudit()",
      );
    }
    const results = [];

    for (let i = 0; i < runs; i++) {
      log(`--- run ${i + 1}/${runs}`);
      const before = parseRows((await getFresh(HISTORY)).doc);
      const beforeKeys = new Set(before.map((r) => r.key));

      const t0 = now();
      await submitFn();
      const tSubmit = now() - t0;

      let tRow = null,
        tLink = null,
        auditId = null,
        polls = 0;
      let serverDateAtRow = null,
        serverDateAtLink = null,
        rowText = null;
      const deadline = now() + 90_000;

      while (now() < deadline) {
        polls++;
        const page = await getFresh(HISTORY);
        const fresh = parseRows(page.doc).find((r) => !beforeKeys.has(r.key));

        if (fresh && tRow === null) {
          tRow = now() - t0;
          serverDateAtRow = page.headers.date;
          rowText = fresh.rowText;
        }
        if (fresh?.linked && tLink === null) {
          tLink = now() - t0;
          serverDateAtLink = page.headers.date;
          auditId = fresh.auditId;
          break;
        }
        await new Promise((r) => setTimeout(r, intervalMs));
      }

      // Server-clock delta: independent of our loop, 1s granularity.
      let serverDeltaS = null;
      if (serverDateAtRow && serverDateAtLink) {
        serverDeltaS =
          (new Date(serverDateAtLink) - new Date(serverDateAtRow)) / 1000;
      }

      const run = {
        run: i + 1,
        submitMs: Math.round(tSubmit),
        rowMs: tRow === null ? null : Math.round(tRow),
        linkMs: tLink === null ? null : Math.round(tLink),
        genMs:
          tRow !== null && tLink !== null ? Math.round(tLink - tRow) : null,
        serverDeltaS,
        polls,
        auditId,
      };
      results.push(run);
      log(`run ${i + 1}:`, run);
      if (rowText) log(`   row: ${rowText.slice(0, 110)}`);
    }

    const linkTimes = results.map((r) => r.linkMs).filter((n) => n !== null);
    if (linkTimes.length) {
      const sorted = [...linkTimes].sort((a, b) => a - b);
      const summary = {
        n: sorted.length,
        minMs: sorted[0],
        medianMs: sorted[Math.floor(sorted.length / 2)],
        maxMs: sorted[sorted.length - 1],
        spreadMs: sorted[sorted.length - 1] - sorted[0],
      };
      console.table([summary]);

      // The safe first-poll delay is the FASTEST observed completion, minus
      // margin — never the median, or fast runs get detected late.
      const safeDelay = Math.max(0, Math.floor(summary.minMs * 0.6));
      log(`fastest completion: ${summary.minMs}ms`);
      log(
        `=> a first-poll delay above ~${safeDelay}ms risks missing fast runs`,
      );
      if (summary.spreadMs > summary.minMs * 0.5) {
        warn(
          `spread is ${summary.spreadMs}ms — high variance; do NOT tune a ` +
            "fixed delay to the median.",
        );
      }
      console.table(results);
      return { results, summary, suggestedFirstPollMs: safeDelay };
    }
    warn("no runs completed");
    return { results, summary: null, suggestedFirstPollMs: null };
  }

  globalThis.verify = { cacheCheck, verifyTiming, getFresh, parseRows };
  log(
    "ready. Run in order:\n" +
      "  await verify.cacheCheck();\n" +
      "  await verify.verifyTiming(() => poc.submitPlannedAudit(), 3);",
  );
})();

// ===================================================================== overhead-audit.js
/**
 * Is OUR code adding latency on top of UT's floor?
 *
 * Separates the preview round trip into:
 *   - UT floor       : time we cannot influence (generation)
 *   - our overhead   : detection lag, redundant fetches, serialization we chose
 *
 * Every check here is read-only except runSequenceTest, which submits one
 * audit. Paste alongside planner-poc.js on a logged-in UT audits page.
 */
(() => {
  const BASE = "https://utdirect.utexas.edu/apps/degree/audits";
  const HISTORY = `${BASE}/submissions/history/`;
  const now = () => performance.now();
  const log = (...a) => console.log("%c[overhead]", "color:#bf5700", ...a);
  const warn = (...a) => console.warn("%c[overhead]", "color:#bf5700", ...a);

  async function getFresh(url) {
    const u = new URL(url);
    u.searchParams.set("_poc", String(Math.random()).slice(2));
    const r = await fetch(u.toString(), {
      credentials: "include",
      cache: "no-store",
      headers: { "Cache-Control": "no-cache" },
    });
    const t = await r.text();
    return { r, text: t, doc: new DOMParser().parseFromString(t, "text/html") };
  }

  /**
   * CHECK 1 — how much of the wait is our detection granularity?
   *
   * A poll loop can only notice completion at cycle boundaries, so on average
   * we waste half a cycle, and up to a full cycle worst case. Measures the
   * real fetch cost instead of assuming it.
   */
  async function detectionOverhead(intervalMs = 150, samples = 8) {
    const times = [];
    for (let i = 0; i < samples; i++) {
      const s = now();
      await getFresh(HISTORY);
      times.push(now() - s);
    }
    const sorted = [...times].sort((a, b) => a - b);
    const fetchMs = Math.round(sorted[Math.floor(samples / 2)]);
    const cycle = fetchMs + intervalMs;
    const out = {
      medianFetchMs: fetchMs,
      sleepMs: intervalMs,
      cycleMs: cycle,
      avgDetectionLagMs: Math.round(cycle / 2),
      worstDetectionLagMs: cycle,
    };
    console.table([out]);
    log(
      `On average we learn the audit is ready ~${out.avgDetectionLagMs}ms ` +
        "after it actually was. That is OUR overhead, not UT's.",
    );
    if (fetchMs > intervalMs * 2) {
      warn(
        `Fetch (${fetchMs}ms) dominates the sleep (${intervalMs}ms) — ` +
          "shortening the sleep further buys almost nothing.",
      );
    }
    return out;
  }

  /**
   * CHECK 2 — is the history page the cheapest thing to poll?
   *
   * We poll a ~40KB page listing every audit, to learn one bit: is the newest
   * one ready. If a smaller endpoint answers the same question, polling gets
   * cheaper and we can poll more often for the same load.
   */
  async function pollTargetCost() {
    const targets = [
      { name: "history (current)", url: HISTORY },
      { name: "audits home", url: `${BASE}/` },
      { name: "requests/history", url: `${BASE}/requests/history/` },
    ];
    const rows = [];
    for (const t of targets) {
      try {
        const s = now();
        const page = await getFresh(t.url);
        rows.push({
          target: t.name,
          ms: Math.round(now() - s),
          kb: Math.round(page.text.length / 1024),
          status: page.r.status,
          hasAuditTable: Boolean(page.doc.querySelector("table")),
        });
      } catch (e) {
        rows.push({
          target: t.name,
          ms: null,
          kb: null,
          status: "ERR",
          hasAuditTable: false,
        });
      }
    }
    console.table(rows);
    log("Cheapest target that still exposes audit state wins.");
    return rows;
  }

  /**
   * CHECK 3 — can we skip the poll entirely?
   *
   * The history row carries a "Submitted (NNNNN)" number distinct from the
   * audit ID. If the submit RESPONSE already contains the eventual audit ID,
   * we could fetch the result directly and delete the detection window.
   *
   * Pass the raw HTML of a submit response (verify.getFresh gives .text).
   */
  function inspectSubmitResponse(html, knownAuditId) {
    if (typeof html !== "string")
      throw new Error("Pass the submit response HTML string.");
    const found = {
      containsKnownId: knownAuditId
        ? html.includes(String(knownAuditId))
        : null,
      // Long digit runs are audit-ID shaped (observed: 100018492357).
      longNumbers: [...new Set(html.match(/\b\d{9,}\b/g) ?? [])].slice(0, 10),
      submittedTokens: [
        ...new Set(html.match(/Submitted\s*\(\d+\)/gi) ?? []),
      ].slice(0, 5),
      resultLinks: [...new Set(html.match(/results\/\d+/g) ?? [])].slice(0, 5),
    };
    console.table([
      {
        containsKnownId: found.containsKnownId,
        longNumbers: found.longNumbers.join(",") || "(none)",
        submitted: found.submittedTokens.join(",") || "(none)",
        resultLinks: found.resultLinks.join(",") || "(none)",
      },
    ]);
    if (found.resultLinks.length || found.containsKnownId) {
      log(
        "PROMISING — the submit response references a result. If that ID is " +
          "the final audit, the poll can be replaced by a direct fetch.",
      );
    } else {
      log(
        "No result reference in the submit response. Polling is required; " +
          "the detection window cannot be removed, only shortened.",
      );
    }
    return found;
  }

  /**
   * CHECK 4 — are our own steps serialized when they need not be?
   *
   * Times the read-only resolve step alone. If it is meaningful and does not
   * depend on the submit, it can overlap with earlier UI work instead of
   * sitting on the critical path.
   */
  // Default term must be a FUTURE one — a past ccyys has no page=4 links and
  // resolve fails. ccyys = YYYY + semester digit (2=spring, 6=summer, 9=fall).
  async function stepIndependence(
    course = { dept: "C S", num: "331", ccyys: "20272" },
  ) {
    if (typeof poc === "undefined")
      throw new Error("Load planner-poc.js first.");
    const s1 = now();
    let resolveMs = null,
      ok = false;
    try {
      await poc.resolveAddLink(course);
      resolveMs = Math.round(now() - s1);
      ok = true;
    } catch (e) {
      warn(`resolve failed (${e.message}) — try a different course/ccyys`);
    }
    const s2 = now();
    await getFresh(HISTORY);
    const historyMs = Math.round(now() - s2);

    const out = {
      resolveMs,
      historySnapshotMs: historyMs,
      // Both are read-only and independent of each other.
      ifRunInParallelMs: ok ? Math.max(resolveMs, historyMs) : null,
      savedMs: ok
        ? resolveMs + historyMs - Math.max(resolveMs, historyMs)
        : null,
    };
    console.table([out]);
    if (ok) {
      log(
        `Resolve and the pre-submit history snapshot are independent ` +
          `read-only calls — running them together saves ~${out.savedMs}ms.`,
      );
    }
    return out;
  }

  globalThis.overhead = {
    detectionOverhead,
    pollTargetCost,
    inspectSubmitResponse,
    stepIndependence,
    getFresh,
  };
  log(
    "ready. All read-only:\n" +
      "  await overhead.detectionOverhead(150);\n" +
      "  await overhead.pollTargetCost();\n" +
      "  await overhead.stepIndependence();\n" +
      "  overhead.inspectSubmitResponse(html, knownAuditId)  // see RUNBOOK",
  );
})();

// ===================================================================== trim-audit.js
/**
 * Trim OUR 25%: which of the ~1.5 s we spend around UT's ~2.1 s can go?
 *
 * The overhead audit told us UT is the floor. This asks the next question:
 * of the time that IS ours, how much is real work and how much is bytes we
 * download and throw away, or fetches we repeat every preview that only need
 * to happen once?
 *
 * Every probe uses the browser's Resource Timing API so a single request is
 * split into redirect / TTFB / download, instead of one opaque elapsed number.
 * That's what tells us whether a stage is UT's server render (immovable) or
 * our own transfer/parse (cuttable).
 *
 * Read-only unless the name says otherwise:
 *   trim.scrapeCost()          read-only  — where do the 395 ms go?
 *   trim.scrapeAlternatives()  read-only  — is there a lighter results page?
 *   trim.formReuse()           read-only  — can the audit form GET be cached?
 *   trim.resolveStability()    read-only  — can resolve be prefetched?
 *   trim.addCost(course)       1 add + 1 delete — page=4 vs landing vs verify
 *   trim.submitCost()          1 audit    — POST without following the redirect
 *   trim.timeTrimmedPreview()  1 audit + 1 add/delete PER RUN — all trims at once
 *   trim.summary()             prints achievable savings from what ran
 *
 * Paste alongside planner-poc.js on a logged-in UT audits page.
 */
(() => {
  const BASE = "https://utdirect.utexas.edu/apps/degree/audits";
  const HISTORY = `${BASE}/submissions/history/`;
  const NEW_AUDIT = `${BASE}/submissions/student_individual/`;
  const PLANNER_VIEW = `${BASE}/planner/view_planner/`;
  const PLANNER_LIST = `${BASE}/planner/ut_course/`;

  // Reference numbers from the 2026-09-09 verified run, so savings print
  // against something. Not measured here.
  const REF = { submitMs: 505, addMs: 345, scrapeMs: 395, resolveMs: 128 };

  const now = () => performance.now();
  const log = (...a) => console.log("%c[trim]", "color:#bf5700", ...a);
  const warn = (...a) => console.warn("%c[trim]", "color:#bf5700", ...a);
  const r0 = (n) => (n == null ? null : Math.round(n));
  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

  const state = { results: {} };
  const keep = (k, v) => ((state.results[k] = v), v);

  performance.setResourceTimingBufferSize(4000);

  function bust(url) {
    const u = new URL(url);
    u.searchParams.set("_poc", String(Math.random()).slice(2));
    return u.toString();
  }

  /**
   * fetch() plus the Resource Timing entry for that exact request.
   * Same-origin, so redirect/ttfb/download are all exposed.
   *
   * Returns ms as: total (our wall clock), redirect (the request that
   * answered with a 3xx — e.g. the page=4 itself), ttfb (server think time
   * on the final URL), download (bytes on the wire), parse (DOMParser, if
   * asked). encodedKb vs decodedKb shows whether UT gzips.
   */
  async function timed(url, init = {}, { parse = false } = {}) {
    const t0 = now();
    const r = await fetch(url, {
      credentials: "include",
      cache: "no-store",
      ...init,
      headers: { "Cache-Control": "no-cache", ...(init.headers ?? {}) },
    });
    const tHead = now();
    const text = r.type === "opaqueredirect" ? "" : await r.text();
    const tBody = now();
    let doc = null;
    if (parse && text) doc = new DOMParser().parseFromString(text, "text/html");
    const tParse = now();

    const e = performance.getEntriesByName(url).at(-1) ?? null;
    const ms = {
      total: r0(tBody - t0),
      redirect: e ? r0(e.redirectEnd - e.redirectStart) : null,
      ttfb: e ? r0(e.responseStart - e.requestStart) : null,
      download: e ? r0(e.responseEnd - e.responseStart) : null,
      parse: parse ? r0(tParse - tBody) : null,
      // Cross-check: fetch resolved (headers) vs body complete.
      headersAt: r0(tHead - t0),
    };
    const kb = {
      encoded: e ? r0(e.encodedBodySize / 1024) : null,
      decoded: e ? r0(e.decodedBodySize / 1024) : r0(text.length / 1024),
    };
    return { r, text, doc, ms, kb, entry: e };
  }

  function parseHistory(doc) {
    const rows = [];
    for (const tr of doc.querySelectorAll("table tbody tr")) {
      const cells = tr.querySelectorAll("td");
      if (cells.length < 8) continue;
      const a = cells[6].querySelector("a");
      rows.push({
        key: [...cells]
          .slice(0, 6)
          .map((c) => c.textContent.trim())
          .join("|"),
        auditId: a?.textContent?.trim() ?? null,
        linked: Boolean(a),
      });
    }
    return rows;
  }

  function plannerRowsIn(doc, base = PLANNER_VIEW) {
    const rows = [];
    for (const link of doc.querySelectorAll('a[href*="action_code=D"]')) {
      const p = new URL(link.getAttribute("href"), base).searchParams;
      if (!p.get("key_course_id")) continue;
      rows.push(
        [p.get("key_course_id"), p.get("key_course_ccyys"), p.get("key_course_seq")]
          .join("|"),
      );
    }
    return rows;
  }

  async function newestAuditId() {
    const page = await timed(bust(HISTORY), {}, { parse: true });
    const row = parseHistory(page.doc).find((r) => r.linked);
    if (!row) throw new Error("No linked audit in history to scrape.");
    return row.auditId;
  }

  /**
   * PROBE 1 — scrape: 395 ms of what?
   *
   * If TTFB dominates, UT is rendering the audit server-side and we can't cut
   * it. If download dominates, the page is heavy — look for a lighter
   * representation (probe 2). If parse dominates, that's our DOMParser and
   * the production parser should be measured the same way.
   */
  async function scrapeCost(auditId, n = 3) {
    auditId ??= await newestAuditId();
    const url = `${BASE}/results/${auditId}/`;
    const runs = [];
    for (let i = 0; i < n; i++) {
      const page = await timed(bust(url), {}, { parse: true });
      runs.push({
        run: i + 1,
        status: page.r.status,
        ...page.ms,
        encodedKb: page.kb.encoded,
        decodedKb: page.kb.decoded,
        gzip: page.r.headers.get("content-encoding") ?? "(none)",
        trCount: page.doc?.querySelectorAll("tr").length ?? null,
      });
      await sleep(300);
    }
    console.table(runs);

    const med = (k) => {
      const v = runs.map((x) => x[k]).filter((x) => x != null).sort((a, b) => a - b);
      return v.length ? v[Math.floor(v.length / 2)] : null;
    };
    const out = keep("scrape", {
      auditId,
      totalMs: med("total"),
      ttfbMs: med("ttfb"),
      downloadMs: med("download"),
      parseMs: med("parse"),
      decodedKb: med("decodedKb"),
      gzip: runs[0].gzip,
    });
    const parts = [
      ["ttfb (UT render)", out.ttfbMs],
      ["download (bytes)", out.downloadMs],
      ["parse (ours)", out.parseMs],
    ].sort((a, b) => b[1] - a[1]);
    log(`scrape median ${out.totalMs}ms — dominated by ${parts[0][0]} (${parts[0][1]}ms)`);
    if (out.gzip === "(none)" && out.decodedKb > 50) {
      warn(`results page is ${out.decodedKb}KB uncompressed — download is a real cost`);
    }
    return out;
  }

  /**
   * PROBE 2 — does UT expose a lighter results representation?
   *
   * Only follows links the results page itself advertises (print, text, pdf,
   * export...). No URL guessing — UT logs every hit.
   */
  async function scrapeAlternatives(auditId) {
    auditId ??= await newestAuditId();
    const url = `${BASE}/results/${auditId}/`;
    const page = await timed(bust(url), {}, { parse: true });
    const seen = new Set();
    const candidates = [];
    for (const a of page.doc.querySelectorAll("a[href]")) {
      const href = new URL(a.getAttribute("href"), url);
      if (href.origin !== new URL(BASE).origin) continue;
      const label = `${a.textContent} ${href.pathname}${href.search}`;
      if (!/print|pdf|text|plain|export|download|csv|summary|compact/i.test(label))
        continue;
      if (seen.has(href.href)) continue;
      seen.add(href.href);
      candidates.push({ text: a.textContent.trim().slice(0, 40), url: href.href });
    }
    // <link rel=alternate> is the polite way to advertise one, if UT does.
    for (const l of page.doc.querySelectorAll('link[rel~="alternate"][href]')) {
      candidates.push({ text: `alternate ${l.getAttribute("type") ?? ""}`, url: new URL(l.getAttribute("href"), url).href });
    }

    const rows = [{ text: "(current results page)", ms: page.ms.total, kb: page.kb.decoded, status: page.r.status }];
    for (const c of candidates.slice(0, 5)) {
      try {
        const alt = await timed(bust(c.url));
        rows.push({ text: c.text, ms: alt.ms.total, kb: alt.kb.decoded, status: alt.r.status, url: c.url });
      } catch (e) {
        rows.push({ text: c.text, ms: null, kb: null, status: "ERR", url: c.url });
      }
    }
    console.table(rows);
    keep("scrapeAlternatives", rows);
    if (rows.length === 1) log("results page advertises no lighter representation — scrape stays as is.");
    else log("Any row cheaper than the current page AND still containing requirement rows is a candidate.");
    return rows;
  }

  /**
   * PROBE 3 — can the audit form GET be done once per session?
   *
   * submitPlannedAudit fetches student_individual/ every preview just to read
   * hidden fields + CSRF. If those fields don't change between fetches and
   * the csrftoken cookie is readable, the fetch is a per-session cost, not a
   * per-preview one.
   */
  async function formReuse() {
    const grab = async () => {
      const page = await timed(bust(NEW_AUDIT), {}, { parse: true });
      const form = [...page.doc.querySelectorAll("form")].find(
        (f) =>
          /test_profile_button/.test(f.getAttribute("action") ?? "") ||
          f.querySelector('[name="incl_planned_crswk"]'),
      );
      if (!form) throw new Error("default audit form not found");
      const fields = {};
      for (const el of form.elements) if (el.name && !el.disabled) fields[el.name] = el.value ?? "";
      return { ms: page.ms.total, fields };
    };
    const a = await grab();
    await sleep(500);
    const b = await grab();

    const changed = Object.keys(a.fields).filter((k) => a.fields[k] !== b.fields[k]);
    const nonCsrfChanged = changed.filter((k) => k !== "csrfmiddlewaretoken");
    const cookieToken = document.cookie.match(/(?:^|;\s*)csrftoken=([^;]+)/)?.[1] ?? null;

    const out = keep("form", {
      formGetMs: r0((a.ms + b.ms) / 2),
      fieldCount: Object.keys(a.fields).length,
      fieldsStable: nonCsrfChanged.length === 0,
      changedFields: nonCsrfChanged.join(",") || "(none)",
      csrfCookieReadable: Boolean(cookieToken),
      // Django masks per-render tokens; the cookie is the unmasked secret. Any
      // masked token from this session validates, so caching one is fine —
      // this just says whether we could skip even that.
      csrfTokenRotatesPerRender: a.fields.csrfmiddlewaretoken !== b.fields.csrfmiddlewaretoken,
    });
    console.table([out]);
    if (out.fieldsStable) {
      log(`form GET (~${out.formGetMs}ms) can run once per session and be reused — fields are stable.`);
    } else {
      warn(`fields change between fetches (${out.changedFields}) — form must be fetched per preview.`);
    }
    return out;
  }

  /**
   * PROBE 4 — is the page=3 listing stable, so resolve can be prefetched?
   *
   * The design forbids constructing page=4 by hand. It does NOT forbid
   * fetching page=3 early (when the user picks a course) and keeping the
   * parsed link. That only works if the link is the same on every fetch.
   */
  async function resolveStability(course = { dept: "C S", num: "331", ccyys: "20272" }) {
    const listUrl =
      `${PLANNER_LIST}?page=3&course_ccyys=${encodeURIComponent(course.ccyys)}` +
      `&course_pass_fail=&s_pf=&course_type=1&dpt=${encodeURIComponent(course.dept)}&s_lvl=U`;
    const hrefsFor = (doc) =>
      [...doc.querySelectorAll('a[href*="page=4"]')]
        .map((a) => a.getAttribute("href"))
        .filter((h) => new URL(h, PLANNER_LIST).searchParams.get("course_num")?.trim() === course.num);

    const a = await timed(bust(listUrl), {}, { parse: true });
    await sleep(500);
    const b = await timed(bust(listUrl), {}, { parse: true });
    const ha = hrefsFor(a.doc), hb = hrefsFor(b.doc);
    const params = ha[0] ? [...new URL(ha[0], PLANNER_LIST).searchParams.keys()] : [];

    const out = keep("resolve", {
      listMs: r0((a.ms.total + b.ms.total) / 2),
      listKb: a.kb.decoded,
      linkFound: ha.length > 0,
      stableAcrossFetches: ha.length > 0 && ha.join() === hb.join(),
      linkParams: params.join(","),
      // Long opaque values suggest a nonce; if none, the link is a pure key.
      looksNonced: ha[0] ? /[0-9a-f]{16,}|[A-Za-z0-9+/=]{24,}/.test(ha[0]) : null,
    });
    console.table([out]);
    if (out.stableAcrossFetches && !out.looksNonced) {
      log(`page=4 link is a stable key — prefetch page=3 when the course is picked; resolve leaves the critical path (~${REF.resolveMs}ms).`);
    } else if (out.linkFound) {
      warn("page=4 link differs between fetches — resolve must stay in the pipeline.");
    }
    return out;
  }

  /**
   * PROBE 5 — add: how much of the 345 ms is the write itself?
   *
   * One real add, timed with Resource Timing so the page=4 request (the
   * 3xx) is separated from the landing page it redirects to. Then checks
   * whether that landing page already lists planner rows — if so, the
   * verify-after-write re-read is a free by-product, not a second fetch.
   *
   * Mutates: adds one row, deletes it via poc.testDelete.
   */
  async function addCost(course = { dept: "C S", num: "324E", ccyys: "20272" }) {
    if (typeof poc === "undefined") throw new Error("Load planner-poc.js first.");

    const before = await timed(bust(PLANNER_VIEW), {}, { parse: true });
    const beforeKeys = new Set(plannerRowsIn(before.doc));

    const tR = now();
    const { href } = await poc.resolveAddLink(course);
    const resolveMs = r0(now() - tR);

    // The write. Followed, so Resource Timing shows both halves.
    const addUrl = new URL(href, PLANNER_LIST).toString();
    const add = await timed(addUrl, {}, { parse: true });
    const landingRows = plannerRowsIn(add.doc, add.r.url);

    const after = await timed(bust(PLANNER_VIEW), {}, { parse: true });
    const afterRows = plannerRowsIn(after.doc);
    const created = afterRows.filter((k) => !beforeKeys.has(k));

    const out = keep("add", {
      resolveMs,
      page4Ms: add.ms.redirect, // the state-changing request alone
      landingTtfbMs: add.ms.ttfb,
      landingDownloadMs: add.ms.download,
      landingKb: add.kb.decoded,
      addTotalMs: add.ms.total,
      landedOn: add.r.url.replace(BASE, ""),
      landingListsRows: landingRows.length > 0,
      landingMatchesPlanner:
        landingRows.length > 0 && landingRows.join() === afterRows.join(),
      verifyReadMs: after.ms.total,
      rowsCreated: created.length,
    });
    console.table([out]);

    if (out.landingMatchesPlanner) {
      log(`landing page IS the planner — skip the verify re-read (~${out.verifyReadMs}ms). Add can be ~${out.page4Ms + out.landingTtfbMs + out.landingDownloadMs}ms.`);
    } else {
      log(`landing page doesn't carry the rows — with redirect:"manual" add is ~${out.page4Ms}ms + verify read ~${out.verifyReadMs}ms.`);
    }

    // Cleanup — hand the row to poc so cleanup() knows about it too.
    if (created.length === 1) {
      const [id, ccyys, seq] = created[0].split("|");
      const row = { key_course_id: id, key_course_ccyys: ccyys, key_course_seq: seq };
      poc.state.added.push(row);
      await poc.testDelete(row);
    } else {
      warn(`expected 1 new row, got ${created.length} — run poc.readPlanner() and clean up manually`);
    }
    return out;
  }

  /**
   * PROBE 6 — submit: stop downloading the page we throw away.
   *
   * The POST redirects to requests/history/ (measured 353 ms). We follow it
   * and discard the HTML. redirect:"manual" returns as soon as UT answers
   * 3xx — the POST is still processed. Confirmed accepted by the row
   * appearing in history, which also re-measures rowVisible / link.
   *
   * Mutates: creates ONE real audit.
   */
  async function submitCost({ intervalMs = 150 } = {}) {
    // Snapshot + form, timed — both are per-preview costs today.
    const hist = await timed(bust(HISTORY), {}, { parse: true });
    const beforeKeys = new Set(parseHistory(hist.doc).map((r) => r.key));

    const formPage = await timed(bust(NEW_AUDIT), {}, { parse: true });
    const form = [...formPage.doc.querySelectorAll("form")].find(
      (f) =>
        /test_profile_button/.test(f.getAttribute("action") ?? "") ||
        f.querySelector('[name="incl_planned_crswk"]'),
    );
    if (!form) throw new Error("default audit form not found");
    const params = new URLSearchParams();
    for (const el of form.elements) if (el.name && !el.disabled) params.append(el.name, el.value ?? "");
    params.set("incl_planned_crswk", "Y");
    const action = new URL(form.getAttribute("action") || "", NEW_AUDIT).toString();
    const csrf = params.get("csrfmiddlewaretoken");

    const post = await timed(action, {
      method: "POST",
      redirect: "manual",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...(csrf ? { "X-CSRFToken": csrf } : {}),
      },
      body: params,
    });
    const tPosted = now();

    // opaqueredirect = UT answered 3xx = accepted (or SSO bounce — the auth
    // gate runs before this in production). basic/200 = re-rendered form =
    // silently rejected.
    const postType = post.r.type;

    let rowMs = null, linkMs = null, auditId = null, polls = 0;
    const deadline = now() + 90_000;
    while (now() < deadline) {
      polls++;
      const page = await timed(bust(HISTORY), {}, { parse: true });
      const fresh = parseHistory(page.doc).find((r) => !beforeKeys.has(r.key));
      if (fresh && rowMs === null) rowMs = r0(now() - tPosted);
      if (fresh?.linked) { linkMs = r0(now() - tPosted); auditId = fresh.auditId; break; }
      await sleep(intervalMs);
    }

    const out = keep("submit", {
      historySnapshotMs: hist.ms.total,
      formGetMs: formPage.ms.total,
      postMs: post.ms.total,
      postTtfbMs: post.ms.ttfb,
      postType,
      accepted: rowMs !== null,
      rowVisibleMs: rowMs,
      linkMs,
      genMs: rowMs != null && linkMs != null ? linkMs - rowMs : null,
      polls,
      auditId,
      savedVsFollowMs: REF.submitMs - post.ms.total,
    });
    console.table([out]);
    if (postType !== "opaqueredirect") {
      warn(`POST returned type=${postType} status=${post.r.status} — expected opaqueredirect. Check accepted.`);
    }
    if (out.accepted) {
      log(`POST without following the redirect: ${out.postMs}ms (was ~${REF.submitMs}ms). Audit ${auditId} queued fine.`);
    } else {
      warn("no new history row within 90 s — the manual-redirect POST may not have been accepted.");
    }
    return out;
  }

  /**
   * PROBE 7 — the trimmed pipeline, end to end.
   *
   * Everything the probes above said is safe, applied at once:
   *   - form fields fetched ONCE for the session, reused per run
   *   - resolve (page=3) + history snapshot + planner snapshot in parallel
   *   - page=4 add with redirect:"manual", one verify read
   *   - POST with redirect:"manual"
   *   - 150 ms serial poll until the ID links, then scrape
   * Per-run stage table + p50 vs the 3639 ms reference budget.
   *
   * Mutates: one planner add/delete and ONE real audit per run.
   */
  async function timeTrimmedPreview(
    course = { dept: "C S", num: "324E", ccyys: "20272" },
    runs = 3,
    { intervalMs = 150 } = {},
  ) {
    if (typeof poc === "undefined") throw new Error("Load planner-poc.js first.");

    // --- once per session -------------------------------------------------
    const tForm = now();
    const formPage = await timed(bust(NEW_AUDIT), {}, { parse: true });
    const form = [...formPage.doc.querySelectorAll("form")].find(
      (f) =>
        /test_profile_button/.test(f.getAttribute("action") ?? "") ||
        f.querySelector('[name="incl_planned_crswk"]'),
    );
    if (!form) throw new Error("default audit form not found");
    const baseParams = [];
    for (const el of form.elements) if (el.name && !el.disabled) baseParams.push([el.name, el.value ?? ""]);
    const action = new URL(form.getAttribute("action") || "", NEW_AUDIT).toString();
    const sessionPrepMs = r0(now() - tForm);
    log(`session prep (form fields, once): ${sessionPrepMs}ms — not on any run's path`);

    const results = [];
    let failures = 0;
    for (let i = 0; i < runs; i++) {
      log(`--- trimmed round trip ${i + 1}/${runs}`);
      const t = { run: i + 1 };
      const tTotal = now();
      let created = [];
      try {
        // --- three independent reads, together -----------------------------
        const tReads = now();
        const [resolved, hist, planner] = await Promise.all([
          poc.resolveAddLink(course),
          timed(bust(HISTORY), {}, { parse: true }),
          timed(bust(PLANNER_VIEW), {}, { parse: true }),
        ]);
        t.readsMs = r0(now() - tReads);
        const beforeHist = new Set(parseHistory(hist.doc).map((r) => r.key));
        const beforePlanner = new Set(plannerRowsIn(planner.doc));

        // --- add, unfollowed -----------------------------------------------
        const tAdd = now();
        const add = await timed(new URL(resolved.href, PLANNER_LIST).toString(), { redirect: "manual" });
        t.addMs = r0(now() - tAdd);
        t.addType = add.r.type;

        const tVerify = now();
        const after = await timed(bust(PLANNER_VIEW), {}, { parse: true });
        t.verifyMs = r0(now() - tVerify);
        created = plannerRowsIn(after.doc).filter((k) => !beforePlanner.has(k));
        if (created.length === 1) {
          const [id, ccyys, seq] = created[0].split("|");
          poc.state.added.push({ key_course_id: id, key_course_ccyys: ccyys, key_course_seq: seq });
        } else {
          throw new Error(`expected 1 new planner row, got ${created.length}`);
        }

        // --- submit, unfollowed --------------------------------------------
        const params = new URLSearchParams(baseParams);
        params.set("incl_planned_crswk", "Y");
        const csrf = params.get("csrfmiddlewaretoken");
        const tPost = now();
        const post = await timed(action, {
          method: "POST",
          redirect: "manual",
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            ...(csrf ? { "X-CSRFToken": csrf } : {}),
          },
          body: params,
        });
        const tPosted = now();
        t.submitMs = r0(tPosted - tPost);
        t.submitType = post.r.type;
        if (post.r.type !== "opaqueredirect") throw new Error(`submit not accepted (type=${post.r.type}, status=${post.r.status})`);

        // --- poll ------------------------------------------------------------
        let rowMs = null, auditId = null;
        const deadline = now() + 90_000;
        while (now() < deadline) {
          const page = await timed(bust(HISTORY), {}, { parse: true });
          const fresh = parseHistory(page.doc).find((r) => !beforeHist.has(r.key));
          if (fresh && rowMs === null) rowMs = r0(now() - tPosted);
          if (fresh?.linked) { auditId = fresh.auditId; break; }
          await sleep(intervalMs);
        }
        if (!auditId) throw new Error("no linked audit within 90 s");
        t.detectMs = rowMs;
        t.genMs = r0(now() - tPosted - rowMs);

        // --- scrape ----------------------------------------------------------
        const tScrape = now();
        const res = await timed(`${BASE}/results/${auditId}/`, {}, { parse: true });
        t.scrapeMs = r0(now() - tScrape);
        t.requirementRows = res.doc.querySelectorAll("tr").length;
        t.auditId = auditId;
        t.totalMs = r0(now() - tTotal);
        results.push(t);
        log("trimmed round trip", t);
        failures = 0;
      } catch (e) {
        warn(`run ${i + 1} failed:`, e);
        if (++failures >= 2) { warn("stopping after 2 consecutive failures"); break; }
      } finally {
        if (created.length === 1) {
          const [id, ccyys, seq] = created[0].split("|");
          const tDel = now();
          await timed(
            `${PLANNER_VIEW}?key_course_id=${encodeURIComponent(id)}` +
              `&key_course_ccyys=${encodeURIComponent(ccyys)}` +
              `&key_course_seq=${encodeURIComponent(seq)}&action_code=D`,
          );
          const check = await timed(bust(PLANNER_VIEW), {}, { parse: true });
          const gone = !plannerRowsIn(check.doc).includes(created[0]);
          t.deleteMs = r0(now() - tDel);
          if (gone) poc.state.added = poc.state.added.filter((r) => r.key_course_seq !== seq);
          else warn("row survived delete — run poc.cleanup()", created[0]);
        }
      }
    }

    if (results.length) {
      console.table(results);
      const p50 = (k) => {
        const v = results.map((r) => r[k]).filter((x) => x != null).sort((a, b) => a - b);
        return v.length ? v[Math.floor(v.length / 2)] : null;
      };
      const stages = ["readsMs", "addMs", "verifyMs", "submitMs", "detectMs", "genMs", "scrapeMs", "totalMs"];
      const row = Object.fromEntries(stages.map((k) => [k, p50(k)]));
      row.sessionPrepMs = sessionPrepMs;
      row.referenceTotalMs = 3639;
      row.savedMs = 3639 - row.totalMs;
      console.table([row]);
      keep("trimmed", { results, p50: row });
      log(`trimmed preview p50 ${row.totalMs}ms vs ${row.referenceTotalMs}ms reference — UT (gen+scrape) is ${Math.round(((row.genMs + row.scrapeMs) / row.totalMs) * 100)}% of it.`);
      return { results, p50: row };
    }
    warn("no runs completed");
    return { results, p50: null };
  }

  /** What could the pipeline look like, given what ran? */
  function summary() {
    const R = state.results;
    const rows = [];
    if (R.submit) {
      rows.push({ stage: "submit POST", nowMs: REF.submitMs, achievableMs: R.submit.postMs, how: 'redirect:"manual"' });
      rows.push({ stage: "history snapshot", nowMs: R.submit.historySnapshotMs, achievableMs: 0, how: "overlap with resolve (proven)" });
    }
    if (R.form) {
      rows.push({ stage: "audit form GET", nowMs: R.form.formGetMs, achievableMs: R.form.fieldsStable ? 0 : R.form.formGetMs, how: R.form.fieldsStable ? "fetch once per session" : "must stay" });
    }
    if (R.add) {
      const a = R.add;
      const ach = a.landingMatchesPlanner
        ? a.page4Ms + a.landingTtfbMs + a.landingDownloadMs
        : a.page4Ms + a.verifyReadMs;
      rows.push({ stage: "add + verify", nowMs: a.addTotalMs + a.verifyReadMs, achievableMs: ach, how: a.landingMatchesPlanner ? "landing page is the verify read" : 'redirect:"manual" + one verify read' });
    }
    if (R.resolve) {
      rows.push({ stage: "resolve (page=3)", nowMs: REF.resolveMs, achievableMs: R.resolve.stableAcrossFetches && !R.resolve.looksNonced ? 0 : REF.resolveMs, how: R.resolve.stableAcrossFetches ? "prefetch at course pick" : "must stay" });
    }
    if (R.scrape) {
      const s = R.scrape;
      rows.push({ stage: "scrape", nowMs: s.totalMs, achievableMs: s.ttfbMs + s.downloadMs, how: `parse ${s.parseMs}ms is ours; ttfb ${s.ttfbMs}ms is UT` });
    }
    for (const r of rows) r.savedMs = r.nowMs - r.achievableMs;
    console.table(rows);
    const saved = rows.reduce((n, r) => n + Math.max(0, r.savedMs), 0);
    log(`total cuttable from what ran: ~${r0(saved)}ms`);
    return rows;
  }

  globalThis.trim = {
    scrapeCost,
    scrapeAlternatives,
    formReuse,
    resolveStability,
    addCost,
    submitCost,
    timeTrimmedPreview,
    summary,
    state,
    timed,
  };
  log(
    "ready. Read-only first:\n" +
      "  await trim.scrapeCost();\n" +
      "  await trim.scrapeAlternatives();\n" +
      "  await trim.formReuse();\n" +
      "  await trim.resolveStability();\n" +
      "then the two that write (1 add+delete, 1 audit):\n" +
      "  await trim.addCost();\n" +
      "  await trim.submitCost();\n" +
      "  trim.summary();\n" +
      "then prove it end to end (1 audit + 1 add/delete per run):\n" +
      "  await trim.timeTrimmedPreview(undefined, 3);",
  );
})();
