#!/usr/bin/env sh
# Concatenate every spike script into all.js — one paste instead of five.
# planner-poc.js goes first; the others read `poc` off globalThis.
# Re-run after editing any script:  sh scripts/spike/bundle.sh
set -e
cd "$(dirname "$0")"
{
  echo "// GENERATED by bundle.sh — edit the source files, not this one."
  echo "// Paste the whole file into a DevTools console on a logged-in UT audits page."
  echo "// Exposes: poc, probe, verify, overhead, trim, effect (see RUNBOOK.md)."
  for f in planner-poc.js generate-timing-probe.js timing-verify.js overhead-audit.js trim-audit.js effect-check.js; do
    echo
    echo "// ===================================================================== $f"
    cat "$f"
  done
} > all.js
node --check all.js
echo "wrote all.js ($(wc -c < all.js | tr -d ' ') bytes)"
